### ISSUE TITLE
running the grabber

### ISSUE THREAD

**Issue by HenrikElias12345** [DamagingRose/Rose-Grabber#136]
When i run the grabber to see if it works, it comes up with this error: 
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "rose_rat.py", line 2, in <module>
ModuleNotFoundError: No module named '__webhook'
```
When i say the grabber i mean the file it generates.
Any fixes?

**Comment by gumbobr0t** [comment]
have you disabled your antivirus and upgraded everything to the latest version?
you can do it with this command:
```bash
pip install -U -r components/scrapedata/requirements.txt
```

dont forget to disable your av and let me know if it works then...

**Comment by HenrikElias12345** [comment]
I just tried the solution and it appears not to work, i still get the same error

**Comment by gumbobr0t** [comment]
show me the tree of the components/source directory pls
**also send me both log files pls `roselog.log` `rosecompile.log`**

**Comment by HenrikElias12345** [comment]
Is this the tree you are looking for ? C:\Users\Administrator\Desktop\Rose-Grabber-main\components

[rosecompile.log](https://github.com/DamagingRose/Rose-Grabber/files/12676132/rosecompile.log)
[roselog.log](https://github.com/DamagingRose/Rose-Grabber/files/12676134/roselog.log)
Let me know if you need anything else

**Comment by gumbobr0t** [comment]
> Is this the tree you are looking for ? C:\Users\Administrator\Desktop\Rose-Grabber-main\components
> 
> [rosecompile.log](https://github.com/DamagingRose/Rose-Grabber/files/12676132/rosecompile.log)
> [roselog.log](https://github.com/DamagingRose/Rose-Grabber/files/12676134/roselog.log)
> Let me know if you need anything else
> 

no, i meant is there any other files that you modified or edited in components/source

**Comment by gumbobr0t** [comment]
also, have you filled out everything on the main tab? (like build-name, icon etc.)

**Comment by gumbobr0t** [comment]
or have you had opened the buikder twice or executed any other python scripts at that time?

**Comment by HenrikElias12345** [comment]
i have not modified any files.
Yes
I dont think so no. 
I can see two other persons in your discord have the same issue

**Comment by HenrikElias12345** [comment]
in the RoseUI folder there is a folder with the name i put on one of my grabbers. and i can see that the file __webhook is not there

**Comment by HenrikElias12345** [comment]
only the _webhook is there

**Comment by gumbobr0t** [comment]
i think they have a different issue with another module, could you check if the __webhook.py file is inside of components/source, if not, your download has been corrupted or your antivirus removed files

**Comment by gumbobr0t** [comment]
> only the _webhook is there

in the source dir is only __webhooks.py?? could you add me on dc
**.gumbobrot**

**Comment by HenrikElias12345** [comment]
I added you

**Comment by HenrikElias12345** [comment]
Got another error after fixing the first one 
`Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "knight_rat.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "discord__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "discord\client.py", line 46, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "discord\ui__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "discord\ui\view.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "discord\ui\item.py", line 45, in <module>
TypeError: type 'Interaction' is not subscriptable`

**Comment by gumbobr0t** [comment]
?
