### ISSUE TITLE
Bootstrap and ransomware issues

### ISSUE THREAD

**Issue by tflsaga** [DamagingRose/Rose-Grabber#157]
**Describe the bug**
Error on launch about bootstrap
**To Reproduce**
Make an exe with all features but special including ransomware no anti vm

**Expected behavior**
Grab passwords and launch ransomware

**Screenshots**

**Desktop (please complete the following information):**
 - win 10 vm
 - chrome
 - latest

Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "sysinf.py", line 58, in <module>
IndexError: list index out of range

also doggo ransomware has no attribute doggo ransomware is still an issue but will probably be fixed soon

**Comment by gumbobrot** [comment]
ah really sorry mate will be fixed really soon

**Comment by something-0001** [comment]
This should be fixed for the most part from testing.

As for the ransomware, I'll look into that more later.

**Comment by gumbobr0t** [comment]
should be fixed, v2.2 is out, try it and tell if its fixed
