### ISSUE TITLE
Bootstrap still messsed up in latest version 

### ISSUE THREAD

**Issue by tflsaga** [DamagingRose/Rose-Grabber#162]
Traceback (most recent call last):
  File "main.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "bin\sysinf.py", line 56, in <module>
IndexError: list index out of range

Using UAC all features grab wallets, ransomware, output exe, inject, startup.

**Comment by gumbobr0t** [comment]
wadahell

**Comment by gumbobr0t** [comment]
ima fix today

**Comment by gumbobr0t** [comment]
should be fixed, can you try again?

**Comment by gumbobr0t** [comment]
closing in 48 hrs if i dont get an answer
@tflsaga

**Comment by tflsaga** [comment]
Bootstrap seems to be fixed, oracle vm won't let me run it because it keeps recognizing as virus though.
I'll try to test somewhere else later, thanks. You can close this issue now. @gumbobr0t

**Comment by gumbobr0t** [comment]
thanks!
