### ISSUE TITLE
Rose Grabber not running

### ISSUE THREAD

**Issue by georgie-dev** [DamagingRose/Rose-Grabber#190]
When I run the builder file, it installs all the packages, when the builder is about to start, it throws an error then closes the command prompt. It closes so fast I can't see the error.
Everything was working fine then all of a sudden I start encountering this issue

**Comment by gumbobr0t** [comment]
hey! please open another command prompt inside the rose grabber directory and run this command:
`call builder.bat` it will output the error  please provide it here

**Comment by georgie-dev** [comment]
[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Starting builder...
Traceback (most recent call last):
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\urllib3\connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\urllib3\util\ssl_.py", line 471, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\urllib3\util\ssl_.py", line 515, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1108, in _create
    self.do_handshake()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\urllib3\connectionpool.py", line 492, in _make_request
    raise new_e
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\urllib3\connectionpool.py", line 470, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\urllib3\connectionpool.py", line 371, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\resources\ui\builder.py", line 47, in <module>
    __devmsg__ = requests.get("https://raw.githubusercontent.com/DamagingRose/Rose-Grabber/main/resources/ui/msg.txt").text.splitlines()[0].split(" - ")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Snacxx\Rose-Grabber-main\Rose-Grabber-main\myvenv\Lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=None)

**Comment by gumbobr0t** [comment]
hey. the issue lies here:
`TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond`

so basically its your connections or githubs api fault, make sure to disable any proxies, vpns or other firewalls and blockers. also verify that your connection is fast enough to establish a connection to github.com. if none of these work, please enable the debug mode on the build file. to do so, you'll need to change the variable inside the resources/ui/builder.py from
```py
__debugm__ = False
```
to
```py
__debugm__ = True
```
This will disable checking for updates so dont establish a connection to github and handle errors more properly.

**Comment by georgie-dev** [comment]
It works now. Had to change my connection. Thanks

**Comment by gumbobr0t** [comment]
okay! enjoy your day! i think i can close this now.
