### ISSUE TITLE
Unhandled exception when trying to run in W11

### ISSUE THREAD

**Issue by cyberhy** [DamagingRose/Rose-Grabber#200]
```
Traceback (most recent call last):
  File "main.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "bin\sysinf.py", line 55, in <module>
  File "subprocess.py", line 466, in check_output
  File "subprocess.py", line 548, in run
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

W11 Sandbox, antivm enabled but i don't think its AntiVM Here.

**Comment by cyberhy** [comment]
I Uninstalled current python & installed 3.11.5 As it was suggested for a similar error to mine, recompiled,  but it did nothing, same error. 
![image](https://github.com/DamagingRose/Rose-Grabber/assets/147515189/ad5d63a5-441e-4cdc-8618-e6c1fabefb18)

**Comment by gumbobr0t** [comment]
send log file

**Comment by cyberhy** [comment]
> send log file

https://paste.ee/p/yP92W

**Comment by gumbobr0t** [comment]
wrong log file. send roselog.log and just upload it here

**Comment by cyberhy** [comment]
> wrong log file. send roselog.log and just upload it here

> wrong log file. send roselog.log and just upload it here

https://paste.ee/p/pYdAx

**Comment by cyberhy** [comment]
> wrong log file. send roselog.log and just upload it here

Too long to upload here, https://paste.ee/p/pYdAx

**Comment by something-0001** [comment]
This looks towards a file which doesn't exist on the system. I'll look into it further.

**Comment by something-0001** [comment]
It's possible the file was never created but yet you tried to open it anyways, as the error no longer occurred after you compiled it.

Regardless, the issue is resolved. I will make a bug-fix in the coming days.
