### ISSUE TITLE
Failed to execute "main" due to unhandled exception: NULL pointer access

### ISSUE THREAD

**Issue by VfxSynth** [DamagingRose/Rose-Grabber#205]
When opening the executable file after building it an error box appears containing:
Traceback (most recent call last):
  File "main.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "bin\sysinf.py", line 61, in <module>
  File "pywifi\iface.py", line 51, in scan_results
  File "pywifi\_wifiutil_win.py", line 264, in scan_results
ValueError: NULL pointer access

**Comment by something-0001** [comment]
Pywifi uses C++, which then uses pointers. The pointer value is weirdly null, which is out of our control. I may look into using a different module, but, unlikely.

Still, make sure you are using Py 3.11.
