### ISSUE TITLE
Grabber not working on targets device, but it works on mine.

### ISSUE THREAD

**Issue by MrGamerCreates** [DamagingRose/Rose-Grabber#208]
When I run the EXE on my VM, it sends the output and info of the VM to my webhook. However, when my target runs the EXE, it gives the error shown below. 

![image](https://github.com/DamagingRose/Rose-Grabber/assets/40676599/329d2db2-d5e0-475e-bbfa-8084fc669f41)

Traceback (most recent call last):
  File "main.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "bin\sysinf.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "wmi.py", line 174, in <module>
  File "win32com\client__init.py", line 86, in GetObject
  File "win32com\client__init.py", line 103, in Moniker
pywintypes.com_error: (-2147217406, 'OLE error 0x80041002', None, None)

What can I do to make it so the EXE works on my victims machine? If it helps, it was compiled on the VM.

**Comment by something-0001** [comment]
The error code provided in the last line can be traced to a certain error Microsoft has documented.

Per Microsoft - This issue occurs because the WMI repository is corrupted.

If it helps, try running it on a different machine if possible.

**Comment by ArjixWasTaken** [comment]
> What can I do to make it so the EXE works on *my victims machine*? If it helps, it was compiled on the VM.

this mf admits that he is using this maliciously

**Comment by something-0001** [comment]
> > What can I do to make it so the EXE works on *my victims machine*? If it helps, it was compiled on the VM.
> 
> this mf admits that he is using this maliciously

True, nothing stops him from downloading code though. Anyways, original reply deleted if it helps.
