### ISSUE TITLE
Rose Ui Builder Stuck In White screen

### ISSUE THREAD

**Issue by rulzzistanz** [DamagingRose/Rose-Grabber#211]
Im using it on VPS And stuck at white screen how i can fix?

**Comment by something-0001** [comment]
> Im using it on VPS And stuck at white screen how i can fix?

Use it on a virtual machine you can host on your own local machine. 

It's possible there's weird things the VPS has that's conflicting with what the code is attempting to do for the builder UI.

**Comment by rulzzistanz** [comment]
Bro im getting now different error

Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 77, in __init__
  File "ctypes\__init__.py", line 376, in __init__
FileNotFoundError: Could not find module 'wlanapi' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "bin\sysinf.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pywifi\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pywifi\wifi.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pywifi\iface.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pywifi\_wifiutil_win.py", line 39, in <module>
  File "ctypes\__init__.py", line 446, in __getattr__
  File "PyInstaller\loader\pyimod03_ctypes.py", line 79, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'wlanapi'. Most likely this dynlib/dll was not found when the application was frozen.

**Comment by something-0001** [comment]
> Bro im getting now different error
> 
> Traceback (most recent call last):   File "PyInstaller\loader\pyimod03_ctypes.py", line 77, in **init**   File "ctypes__init__.py", line 376, in **init** FileNotFoundError: Could not find module 'wlanapi' (or one of its dependencies). Try using the full path with constructor syntax.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):   File "main.py", line 37, in   File "", line 1176, in _find_and_load   File "", line 1147, in _find_and_load_unlocked   File "", line 690, in _load_unlocked   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module   File "bin\sysinf.py", line 7, in   File "", line 1176, in _find_and_load   File "", line 1147, in _find_and_load_unlocked   File "", line 690, in _load_unlocked   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module   File "pywifi__init__.py", line 15, in   File "", line 1176, in _find_and_load   File "", line 1147, in _find_and_load_unlocked   File "", line 690, in _load_unlocked   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module   File "pywifi\wifi.py", line 15, in   File "", line 1176, in _find_and_load   File "", line 1147, in _find_and_load_unlocked   File "", line 690, in _load_unlocked   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module   File "pywifi\iface.py", line 11, in   File "", line 1176, in _find_and_load   File "", line 1147, in _find_and_load_unlocked   File "", line 690, in _load_unlocked   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module   File "pywifi_wifiutil_win.py", line 39, in   File "ctypes__init__.py", line 446, in **getattr**   File "PyInstaller\loader\pyimod03_ctypes.py", line 79, in **init** pyimod03_ctypes.install..PyInstallerImportError: Failed to load dynlib/dll 'wlanapi'. Most likely this dynlib/dll was not found when the application was frozen.

The builder should not be in an executable.

**Comment by rulzzistanz** [comment]
i tried .scr its not working still

**Comment by something-0001** [comment]
> i tried .scr its not working still

Delete Rose Grabber, redownload it from the repository, run `builder.bat`

**Comment by gumbobr0t** [comment]
closing due to inactivity. i assume its fixed because of no response. further reports of this wont really help, its out of our control
