### ISSUE TITLE
Exe doesnt work

### ISSUE THREAD

**Issue by trixymgk** [DamagingRose/Rose-Grabber#213]
Traceback (most recent call last):
  File "main.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "bin\sysinf.py", line 61, in <module>
  File "pywifi\iface.py", line 51, in scan_results
  File "pywifi_wifiutil_win.py", line 264, in scan_results
ValueError: NULL pointer access
What can i do?

**Comment by something-0001** [comment]
Duplicate.
